export default {
    TASKS_GET: "TASKS_GET",
    TASKS_SAVE: "TASKS_SAVE",
    TASKS_DELETE: "TASKS_DELETE",
    TASKS_UPDATE: "TASKS_UPDATE",
    INCREMENT_COUNTER: "INCREMENT_COUNTER",
    DECREMENT_COUNTER: "DECREMENT_COUNTER"
}